export const ADD_ORDER = 'ADD_ORDER';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const UPDATE_ITEM_FROM_CART = 'UPDATE_ITEM_FROM_CART'; 

export const SET_PRODUCTS = 'SET_PRODUCTS';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED';